version: '3'
services:
    web:
        container_name: nginx
        image: gbsoftwaresolutions/nginx-dev
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/conf/configs:/configs
            - ./.docker/workspace:/workspace
        ports:
            - 8886:8886
        restart: always
        depends_on:
            - php
            - db
    php:
        container_name: php
        image: gbsoftwaresolutions/php74-dev
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/configs:/configs
            - ./.docker/workspace:/workspace
    composer:
        image: composer
        volumes:
            - .:/app
        command: install
    db: 
        container_name: db
        image: gbsoftwaresolutions/postgres-dev
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        volumes:
            - ./.docker/postgresql/:/var/lib/postgresql
            - ./.docker/postgresql/data:/var/lib/postgresql/data

volumes:
    pgadmin:

networks:
  default:
    name: external-dev
