version: '3'
services:
    web:
        container_name: nginx
        image: gbsoftwaresolutions/nginx-dev
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/workspace:/workspace
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db
    php:
        container_name: php
        image: gbsoftwaresolutions/php74-dev
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/workspace:/workspace
    composer:
        image: composer
        volumes:
            - .:/app
        command: install
    db: 
        container_name: db
        image: gbsoftwaresolutions/postgres-dev
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/

    # pgadmin:
    #     container_name: pgadmin_container
    #     image: dpage/pgadmin4
    #     links:
    #         - db
    #     depends_on: 
    #         - db
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}'
    #         PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD:-adminstsapi}'
    #     volumes:
    #         - 'pgadmin:/root/.pgadmin'
    #     ports:
    #         - '${PGADMIN_PORT:-5050}:80'
    #     restart: unless-stopped

    # mailcatcher:
    #     restart: on-failure:10
    #     image: dockage/mailcatcher:0.7.1
    #     ports:
    #     - "1080:1080"
    #     - "1025:1025"

    # redis:
    #     image: redis:5-alpine
    #     ports: [6379]

    # rabbitmq:
    #     image: rabbitmq:3.7-management
    #     ports: [5672,15672]

volumes:
    pgadmin:

networks:
  default:
    name: external-dev
